const data = [
    {
      num: '1',
      name: 'Большой шар с рисунком',
      count: '2400',
      year: '2001',
      shape: 'шар',
      color: 'желтый',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/shar-elochnyy-8-sm-d-324-2-akril-opal-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '2',
      name: 'Зелёный шар с цветами',
      count: '5500',
      year: '2000',
      shape: 'шар',
      color: 'зелёный',
      size: 'большой',
      favorite: false,
      src:'https://ugolok.by/image/cache/catalog/novogodniy-shar-8-sm-d-192-butylochnyy-matovyy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '3',
      name: 'Красный матовый шар',
      count: '3500',
      year: '2002',
      shape: 'шар',
      color: 'красный',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/shar-elochnyy-8-sm-d-323-krasnyy-matovyy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '4',
      name: 'Сосулька красная',
      count: '2500',
      year: '2004',
      shape: 'фигурка',
      color: 'красный',
      size: 'большой',
      favorite: false,
      src: 'https://ae01.alicdn.com/kf/Hc1864bd8b80c487681e4dd63edd50a7dF.jpeg'
    },
    {
      num: '5',
      name: 'Красный виноград',
      count: '4800',
      year: '2021',
      shape: 'фигурка',
      color: 'красный',
      size: 'средний',
      favorite: true,
      src:'https://ugolok.by/image/cache/catalog/elochnyy-shar-8-sm-d-335-krasnyy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '6',
      name: 'Красный шар с рисунком',
      count: '4600',
      year: '2010',
      shape: 'шар',
      color: 'красный',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/shar-elochnyy-8-sm-d-323-krasnyy-matovyy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '7',
      name: 'Молочно-белый шар',
      count: '1200',
      year: '2012',
      shape: 'шар',
      color: 'белый',
      size: 'средний',
      favorite: true,
      src: 'https://ugolok.by/image/cache/catalog/elochnyy-shar-8-sm-d-17-belyy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '8',
      name: 'Красный шар',
      count: '1000',
      year: '2010',
      shape: 'шар',
      color: 'красный',
      size: 'большой',
      favorite: false,
      src:'https://ugolok.by/image/cache/catalog/novogodniy-shar-8-sm-d-334-krasnyy-opal-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '9',
      name: 'Колокольчик старинный',
      count: '2800',
      year: '2005',
      shape: 'колокольчик',
      color: 'белый',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/elochnaya-igrushka-kolokolchik-belyy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '10',
      name: 'Белый шар ретро',
      count: '740',
      year: '2007',
      shape: 'шар',
      color: 'белый',
      size: 'большой',
      favorite: false,
      src:'https://ugolok.by/image/cache/catalog/Orbital/shar-yolochnyj-8-sm-d-258-belyj-matovyj-ruchnaya-rabota1-650x650.jpg'
    },
    {
      num: '11',
      name: 'Шишка еловая белая',
      count: '11',
      year: '2007',
      shape: 'шишка',
      color: 'белый',
      size: 'малый',
      favorite: false,
      src:'https://ugolok.by/image/cache/catalog/novogodnee-ukrashenie-shishka-sosnovaya-belaya-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '12',
      name: 'Белый шар с цветами',
      count: '5555',
      year: '2008',
      shape: 'шар',
      color: 'белый',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/novogodniy-shar-8-sm-d-384-belyy-opal-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '13',
      name: 'Шар расписной Река',
      count: '3300',
      year: '2013',
      shape: 'шар',
      color: 'синий',
      size: 'большой',
      favorite: true,
      src: 'https://ugolok.by/image/cache/catalog/Orbital/shar-yolochnyj-8-sm-d-258-sinij2-650x650.jpg'
    },
    {
      num: '14',
      name: 'Шар расписной Деревня',
      count: '4400',
      year: '2014',
      shape: 'шар',
      color: 'синий',
      size: 'большой',
      favorite: true,
      src: 'https://ugolok.by/image/cache/catalog/shar-elochnyy-8-sm-d-258-siniy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '15',
      name: 'Колокольчик расписной',
      count: '3333',
      year: '1970',
      shape: 'колокольчик',
      color: 'синий',
      size: 'средний',
      favorite: false,
      src: 'https://4eli.ru/upload/iblock/a30/a30a490ee1ae83d8515948ca91092c47.jpg'
    },
    {
      num: '16',
      name: 'Шишка расписная Пейзаж',
      count: '2300',
      year: '2006',
      shape: 'шишка',
      color: 'синий',
      size: 'средний',
      favorite: true,
      src: 'https://cdn1.ozone.ru/s3/multimedia-r/c1200/6163047087.jpg'
    },
    {
      num: '17',
      name: 'Шишка расписная',
      count: '3700',
      year: '2002',
      shape: 'шишка',
      color: 'красный',
      size: 'средний',
      favorite: false,
      src: 'https://avatars.mds.yandex.net/get-mpic/5252277/img_id3507929191436785051.jpeg/orig'
    },
    {
      num: '18',
      name: 'Желтый шар с бантом',
      count: '2000',
      year: '2010',
      shape: 'шар',
      color: 'желтый',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/novogodniy-shar-8-sm-d-250-temno-zolotoy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '19',
      name: 'Желтый шар с паетками',
      count: '1200',
      year: '2002',
      shape: 'шар',
      color: 'желтый',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/novogodniy-shar-8-sm-gliter-zheltyy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '20',
      name: 'Красный шар с бантом',
      count: '800',
      year: '2009',
      shape: 'шар',
      color: 'красный',
      size: 'средний',
      favorite: true,
      src: 'https://ugolok.by/image/cache/catalog/novogodniy-shar-8-sm-d-215-krasnyy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '21',
      name: 'Красный шар с звёздами',
      count: '4000',
      year: '2009',
      shape: 'шар',
      color: 'красный',
      size: 'большой',
      favorite: true,
      src: 'https://ugolok.by/image/cache/catalog/Orbital/shar-yolochnyj-8-sm-d-222-krasnyj2-650x650.jpg'
    },
    {
      num: '22',
      name: 'Шишка еловая золотая',
      count: '1100',
      year: '2009',
      shape: 'шишка',
      color: 'желтый',
      size: 'малый',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/novogodnee-ukrashenie-shishka-sosnovaya-med-s-belym-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '23',
      name: 'Колокольчик старинный',
      count: '900',
      year: '2011',
      shape: 'колокольчик',
      color: 'желтый',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/Orbital/yolochnaya-igrushka-kolokolchik-krasnyj-650x650.jpg'
    },
    {
      num: '24',
      name: 'Снежинка изящная',
      count: '1000',
      year: '2013',
      shape: 'снежинка',
      color: 'белый',
      size: 'большой',
      favorite: false,
      src: 'https://cdn1.ozone.ru/s3/multimedia-4/c1200/6068202796.jpg'
    },
    {
      num: '25',
      name: 'Розовый шар с блёстками',
      count: '1200',
      year: '2017',
      shape: 'шар',
      color: 'красный',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/novogodniy-shar-8-sm-d-294-2-rozovyy-opal-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '26',
      name: 'Рубиново-золотой шар',
      count: '800',
      year: '2018',
      shape: 'шар',
      color: 'желтый',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/novogodniy-shar-8-sm-gliter-zheltyy-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '27',
      name: 'Красный шар с узором',
      count: '900',
      year: '2019',
      shape: 'шар',
      color: 'красный',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/Orbital/shar-yolochnyj-8-sm-d-222-krasnyj2-650x650.jpg'
    },
    {
      num: '28',
      name: 'Бордовый шар с узором',
      count: '1000',
      year: '2019',
      shape: 'шар',
      color: 'красный',
      size: 'большой',
      favorite: false,
      src: 'https://ugolok.by/image/cache/catalog/Orbital/novogodnij-shar-8-sm-sh-319-krasnyj-matovyj-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '29',
      name: 'Старинный шар с цветами',
      count: '500',
      year: '2009',
      shape: 'шар',
      color: 'желтый',
      size: 'большой',
      favorite: true,
      src: 'https://ugolok.by/image/cache/catalog/shar-elochnyy-8-sm-d-324-2-akril-opal-ruchnaya-rabota-650x650.jpg'
    },
    {
      num: '30',
      name: 'Старинный шар с узором',
      count: '800',
      year: '2022',
      shape: 'шар',
      color: 'желтый',
      size: 'большой',
      favorite: true,
      src: 'https://coberu.ru/files/coins/737602/detail_elochnaya_igrushka_shar_steklo_simvol_goda_krysa_mysh_75sm_art3211_id1964.jpg'
    },

  ];
  
  export default data;